# Generated by Django 3.2 on 2025-02-19 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='articles/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Bachelier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('programme', models.CharField(max_length=100)),
                ('moyenne', models.CharField(max_length=10)),
                ('mention', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_diplome', models.CharField(choices=[('Licence', 'Licence'), ('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Bacc2', 'Bacc2'), ('Bac unique', 'Bac unique'), ('Post-secondaire', 'Post-secondaire'), ('NS4', 'NS4')], max_length=50)),
                ('institution', models.CharField(max_length=255)),
                ('annee', models.PositiveIntegerField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ueh.departement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ueh.adresse')),
                ('entites', models.ManyToManyField(blank=True, to='ueh.Entite')),
                ('etudes', models.ManyToManyField(blank=True, to='ueh.Etude')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='ueh.departement')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ueh.commune'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ueh.departement'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
