# Generated by Django 3.2 on 2025-02-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='MENFP', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
