# Generated by Django 4.2.16 on 2025-04-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueh', '0002_auto_20250218_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Terminé'), ('active', 'En cours'), ('upcoming', 'À venir')], max_length=20)),
            ],
        ),
    ]
