# Generated by Django 4.2.16 on 2025-04-29 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueh', '0003_examen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='date',
            field=models.DateField(),
        ),
    ]
