# Generated by Django 4.2.16 on 2025-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ueh', '0004_alter_examen_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='departement',
        ),
        migrations.DeleteModel(
            name='Diplome',
        ),
        migrations.RemoveField(
            model_name='etude',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='etude',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='entites',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='etudes',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='utilisateur',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Commune',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Entite',
        ),
        migrations.DeleteModel(
            name='Etude',
        ),
        migrations.DeleteModel(
            name='Profil',
        ),
    ]
