# Generated by Django 4.2.23 on 2025-09-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunexe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bachelier',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='bachelier',
            name='moyenne',
        ),
        migrations.AddField(
            model_name='bachelier',
            name='nb_recherches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
