# Generated by Django 4.2.23 on 2025-09-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunexe', '0002_remove_bachelier_mention_remove_bachelier_moyenne_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifications', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='bachelier',
            name='nb_recherches',
        ),
    ]
