# Generated by Django 4.2.23 on 2025-09-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunexe', '0003_verification_remove_bachelier_nb_recherches'),
    ]

    operations = [
        migrations.AddField(
            model_name='bachelier',
            name='annee_bac',
            field=models.IntegerField(default=2025),
        ),
    ]
